kind: Deployment
apiVersion: apps/v1
metadata:
  name: mydeployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: helloapp
  template:
    metadata:
      labels:
        app: helloapp
    spec:
      containers:
        - name: hellcont
          image: tomcat
          ports:
            - containerPort: 8080
